### Get all credentials

GET http://localhost:3000/api/credentials

### Get single credential

GET http://localhost:3000/api/credentials/google

### Add single credential

POST  http://localhost:3000/api/credentials
Content-Type: application/json

{
    "service": "neuefische",
    "username": "christoph",
    "password": "123456789"
}

### Delete credential

DELETE http://localhost:3000/api/credentials/neuefische