### Get all credentials
GET http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}

### Get single credential
GET http://localhost:3000/api/credentials/altefische
Authorization: {{$dotenv MASTERPASSWORD}}

### Add single credential
POST http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}
Content-Type: application/json

{
    "service": "github",
    "username": "Chris",
    "password": "12345678910"
}

### Delete single credential
DELETE http://localhost:3000/api/credentials/neuefische
Authorization: {{$dotenv MASTERPASSWORD}}

### Modify existing credential
PATCH http://localhost:3000/api/credentials/binance
Authorization: {{$dotenv MASTERPASSWORD}}
Content-Type: application/json

{
    "service": "binance",
    "username": "Christoph Schmitz",
    "password": "1337"
}