### Get all credentials

GET http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}
### Get single credential

GET http://localhost:3000/api/credentials/google
Authorization: {{$dotenv MASTERPASSWORD}}
### Add single credential

POST  http://localhost:3000/api/credentials/
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "neuefische",
    "username": "christoph",
    "password": "123456789"
}

### Delete credential

DELETE http://localhost:3000/api/credentials/neuefische
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}
## Put credential

### Replace existing credential
PUT http://localhost:3000/api/credentials/neuefische
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "StudiVZ",
    "username": "christoph",
    "password": "123456789"
} 